function MDH:GetLoadPresetGeneratorFunction()
    return function(owner, rootDescription)
        rootDescription:CreateTitle(UTILS:TableLength(MDH.db.global.presets) == 0 and "No presets available" or
                                        "Presets available");

        for key, value in pairs(MDH.db.global.presets) do
            rootDescription:CreateButton(value.name, function(data)
                MDH:ExecutePreset(value);
            end);
        end
    end
end

function MDH:ExecutePreset(preset)
    MailFrameTab_OnClick(_G["MailFrameTab2"]);
    ClearAllMailSlots();

    SendMailNameEditBox:SetText(preset.to);
    SendMailSubjectEditBox:SetText("MDH - Generated by preset [" .. preset.name .. "]");
    local itemGroupFunctions = {};

    for key, value in pairs((preset.itemGroups or {})) do
        if (value) then
            tinsert(itemGroupFunctions, MDH.ItemGroupOptions[key].checkItemBelongsToGroup);
        end
    end

    for bag = 0, 4 do -- Loops through bags 0 (backpack) to 4 (bags)
        for slot = 1, C_Container.GetContainerNumSlots(bag) do
            local itemLink = C_Container.GetContainerItemLink(bag, slot);

            if (itemLink and ItemShouldBeAdded(itemLink, itemGroupFunctions, preset.custom, preset.exclusion)) then
                if (not AddItemToNextEmptyMailSlot(bag, slot)) then
                    return;
                end
            end
        end
    end
end

function ItemLinkIsMemberOfGroup(itemLink, itemGroupFunctions)
    for key, fn in pairs(itemGroupFunctions) do
        if (fn(itemLink)) then
            return true;
        end
    end

    return false;
end

function ItemShouldBeAdded(itemLink, itemGroupFunctions, customItems, excludedItems)
    return not ItemIsMemberOfList(itemLink, excludedItems) and
               (ItemLinkIsMemberOfGroup(itemLink, itemGroupFunctions) or ItemIsMemberOfList(itemLink, customItems));
end

function ItemIsMemberOfList(itemLink, list)
    if (not list or #list == 0) then
        return false;
    end

    for key, customItemLink in pairs(list) do
        if (itemLink == customItemLink) then
            return true;
        end
    end

    return false;
end

function AddItemToNextEmptyMailSlot(bag, slot)
    for mailSlot = 1, ATTACHMENTS_MAX_SEND do
        if (not HasSendMailItem(mailSlot)) then
            C_Container.PickupContainerItem(bag, slot);
            ClickSendMailItemButton(mailSlot);
            return true;
        end
    end

    return false;
end

function ClearAllMailSlots()
    for i = 1, ATTACHMENTS_MAX_SEND do
        ClickSendMailItemButton(i, true);
    end
end
