---@type string, table
local addonName, addonTable = ...;

---@class ClassicItems
addonTable.classicItems = {
  ---@type PresetItemsDBItem[]
  explosives = {
    { itemID = 16040, name = "Arcane Bomb" },
    { itemID = 4380,  name = "Big Bronze Bomb" },
    { itemID = 4394,  name = "Big Iron Bomb" },
    { itemID = 4365,  name = "Coarse Dynamite" },
    { itemID = 16005, name = "Dark Iron Bomb" },
    { itemID = 18641, name = "Dense Dynamite" },
    { itemID = 4384,  name = "Explosive Sheep" },
    { itemID = 6714,  name = "Ez-Thro Dynamite" },
    { itemID = 18588, name = "Ez-Thro Dynamite II" },
    { itemID = 4852,  name = "Flash Bomb" },
    { itemID = 10580, name = "Goblin \"Boom\" Box" },
    { itemID = 4395,  name = "Goblin Land Mine" },
    { itemID = 10646, name = "Goblin Sapper Charge" },
    { itemID = 4378,  name = "Heavy Dynamite" },
    { itemID = 10562, name = "Hi-Explosive Bomb" },
    { itemID = 4390,  name = "Iron Grenade" },
    { itemID = 4370,  name = "Large Copper Bomb" },
    { itemID = 4398,  name = "Large Seaforium Charge" },
    { itemID = 10514, name = "Mithril Frag Bomb" },
    { itemID = 18594, name = "Powerful Seaforium Charge" },
    { itemID = 4360,  name = "Rough Copper Bomb" },
    { itemID = 4358,  name = "Rough Dynamite" },
    { itemID = 4374,  name = "Small Bronze Bomb" },
    { itemID = 4367,  name = "Small Seaforium Charge" },
    { itemID = 10507, name = "Solid Dynamite" },
    { itemID = 10586, name = "The Big One" },
    { itemID = 15993, name = "Thorium Grenade" },
  },
  ---@type PresetItemsDBItem[]
  elemental = {
    -- Water
    { itemID = 7070,  name = "Elemental Water" },
    { itemID = 7079,  name = "Globe of Water" },
    { itemID = 7080,  name = "Essence of Water" },
    -- Fire
    { itemID = 7068,  name = "Elemental Fire" },
    { itemID = 7077,  name = "Heart of Fire" },
    { itemID = 7078,  name = "Essence of Fire" },
    -- Air
    { itemID = 7069,  name = "Elemental Air" },
    { itemID = 7081,  name = "Breath of Wind" },
    { itemID = 7082,  name = "Essence of Air" },
    -- Earth
    { itemID = 7067,  name = "Elemental Earth" },
    { itemID = 7075,  name = "Core of Earth" },
    { itemID = 7076,  name = "Essence of Earth" },
    -- Undeath
    { itemID = 7972,  name = "Ichor of Undeath" },
    { itemID = 12808, name = "Essence of Undeath" },
    -- Life
    { itemID = 10286, name = "Heart of the Wild" },
    { itemID = 12803, name = "Living Essence" },
  },
  ---@type PresetItemsDBItem[]
  stone = {
    { itemID = 2835,  name = "Rough Stone" },
    { itemID = 2836,  name = "Coarse Stone" },
    { itemID = 2838,  name = "Heavy Stone" },
    { itemID = 7912,  name = "Solid Stone" },
    { itemID = 12365, name = "Dense Stone" },
  },
  ---@type PresetItemsDBItem[]
  gem = {
    { itemID = 7909,  name = "Aquamarine" },
    { itemID = 12363, name = "Arcane Crystal" },
    { itemID = 12800, name = "Azerothian Diamond" },
    { itemID = 7971,  name = "Black Pearl" },
    { itemID = 11382, name = "Blood of the Mountain" },
    { itemID = 12361, name = "Blue Sapphire" },
    { itemID = 3864,  name = "Citrine" },
    { itemID = 13926, name = "Golden Pearl" },
    { itemID = 12364, name = "Huge Emerald" },
    { itemID = 5500,  name = "Iridescent Pearl" },
    { itemID = 1529,  name = "Jade" },
    { itemID = 24478, name = "Jaggal Pearl" },
    { itemID = 12799, name = "Large Opal" },
    { itemID = 1705,  name = "Lesser Moonstone" },
    { itemID = 774,   name = "Malachite" },
    { itemID = 1206,  name = "Moss Agate" },
    { itemID = 24479, name = "Shadow Pearl" },
    { itemID = 1210,  name = "Shadowgem" },
    { itemID = 5498,  name = "Small Lustrous Pearl" },
    { itemID = 19774, name = "Souldarite" },
    { itemID = 7910,  name = "Star Ruby" },
    { itemID = 818,   name = "Tigerseye" },
  },
  ---@type PresetItemsDBItem[]
  enchant = {
    { itemID = 6217,  name = "Copper Rod" },
    { itemID = 6218,  name = "Runed Copper Rod" },
    { itemID = 6216,  name = "Mystical Powder" },
    { itemID = 10940, name = "Strange Dust" },
    { itemID = 10938, name = "Lesser Magic Essence" },
    { itemID = 10939, name = "Greater Magic Essence" },
    { itemID = 6338,  name = "Silver Rod" },
    { itemID = 10998, name = "Lesser Astral Essence" },
    { itemID = 6339,  name = "Runed Silver Rod" },
    { itemID = 10978, name = "Small Glimmering Shard" },
    { itemID = 6374,  name = "Enchanted Powder" },
    { itemID = 11083, name = "Soul Dust" },
    { itemID = 11082, name = "Greater Astral Essence" },
    { itemID = 11084, name = "Large Glimmering Shard" },
    { itemID = 11128, name = "Golden Rod" },
    { itemID = 11130, name = "Runed Golden Rod" },
    { itemID = 11134, name = "Lesser Mystic Essence" },
    { itemID = 11138, name = "Small Glowing Shard" },
    { itemID = 11137, name = "Vision Dust" },
    { itemID = 11135, name = "Greater Mystic Essence" },
    { itemID = 11139, name = "Large Glowing Shard" },
    { itemID = 11177, name = "Small Radiant Shard" },
    { itemID = 11144, name = "Truesilver Rod" },
    { itemID = 11174, name = "Lesser Nether Essence" },
    { itemID = 11145, name = "Runed Truesilver Rod" },
    { itemID = 11176, name = "Dream Dust" },
    { itemID = 11178, name = "Large Radiant Shard" },
    { itemID = 11175, name = "Greater Nether Essence" },
    { itemID = 14343, name = "Small Brilliant Shard" },
    { itemID = 16202, name = "Lesser Eternal Essence" },
    { itemID = 16206, name = "Arcanite Rod" },
    { itemID = 14344, name = "Large Brilliant Shard" },
    { itemID = 16203, name = "Greater Eternal Essence" },
    { itemID = 16204, name = "Illusion Dust" },
    { itemID = 16207, name = "Runed Arcanite Rod" },
    { itemID = 20725, name = "Nexus Crystal" },
  },
  ---@type PresetItemsDBItem[]
  cloth = {
    { itemID = 2589,  name = "Linen Cloth" },
    { itemID = 2320,  name = "Coarse Thread" },
    { itemID = 2996,  name = "Bolt of Linen Cloth" },
    { itemID = 2592,  name = "Wool Cloth" },
    { itemID = 3182,  name = "Spider's Silk" },
    { itemID = 2321,  name = "Fine Thread" },
    { itemID = 2997,  name = "Bolt of Woolen Cloth" },
    { itemID = 4306,  name = "Silk Cloth" },
    { itemID = 4291,  name = "Silken Thread" },
    { itemID = 4305,  name = "Bolt of Silk Cloth" },
    { itemID = 4337,  name = "Thick Spider's Silk" },
    { itemID = 4338,  name = "Mageweave Cloth" },
    { itemID = 10285, name = "Shadow Silk" },
    { itemID = 8343,  name = "Heavy Silken Thread" },
    { itemID = 4339,  name = "Bolt of Mageweave" },
    { itemID = 14256, name = "Felcloth" },
    { itemID = 14047, name = "Runecloth" },
    { itemID = 14341, name = "Rune Thread" },
    { itemID = 14227, name = "Ironweb Spider Silk" },
    { itemID = 14342, name = "Mooncloth" },
    { itemID = 14048, name = "Bolt of Runecloth" },
  },
  ---@type PresetItemsDBItem[]
  herb = {
    { itemID = 22710, name = "Bloodthistle" },
    { itemID = 2447,  name = "Peacebloom" },
    { itemID = 2449,  name = "Earthroot" },
    { itemID = 765,   name = "Silverleaf" },
    { itemID = 785,   name = "Mageroyal" },
    { itemID = 2452,  name = "Swiftthistle" },
    { itemID = 2450,  name = "Briarthorn" },
    { itemID = 3820,  name = "Stranglekelp" },
    { itemID = 2453,  name = "Bruiseweed" },
    { itemID = 3355,  name = "Wild Steelbloom" },
    { itemID = 3356,  name = "Kingsblood" },
    { itemID = 3369,  name = "Grave Moss" },
    { itemID = 3357,  name = "Liferoot" },
    { itemID = 3818,  name = "Fadeleaf" },
    { itemID = 3821,  name = "Goldthorn" },
    { itemID = 3358,  name = "Khadgar's Whisker" },
    { itemID = 3819,  name = "Wintersbite" },
    { itemID = 8153,  name = "Wildvine" },
    { itemID = 4625,  name = "Firebloom" },
    { itemID = 8831,  name = "Purple Lotus" },
    { itemID = 8836,  name = "Arthas' Tears" },
    { itemID = 8838,  name = "Sungrass" },
    { itemID = 8845,  name = "Ghost Mushroom" },
    { itemID = 8839,  name = "Blindweed" },
    { itemID = 8846,  name = "Gromsblood" },
    { itemID = 13464, name = "Golden Sansam" },
    { itemID = 13463, name = "Dreamfoil" },
    { itemID = 13465, name = "Mountain Silversage" },
    { itemID = 13466, name = "Plaguebloom" },
    { itemID = 13467, name = "Icecap" },
    { itemID = 13468, name = "Black Lotus" },
    { itemID = 19726, name = "Bloodvine" },
    { itemID = 19727, name = "Blood Scythe" },
  },
  ---@type PresetItemsDBItem[]
  ore = {
    { itemID = 2775,  name = "Silver Ore" },
    { itemID = 2770,  name = "Copper Ore" },
    { itemID = 2771,  name = "Tin Ore" },
    { itemID = 2776,  name = "Gold Ore" },
    { itemID = 2772,  name = "Iron Ore" },
    { itemID = 3858,  name = "Mithril Ore" },
    { itemID = 10620, name = "Thorium Ore" },
    { itemID = 7911,  name = "Truesilver Ore" },
    { itemID = 11370, name = "Dark Iron Ore" },
    { itemID = 12809, name = "Guardian Stone" },
    { itemID = 18562, name = "Elementium Ore" },
  },
  ---@type PresetItemsDBItem[]
  bar = {
    { itemID = 2842,  name = "Silver Bar" },
    { itemID = 2840,  name = "Copper Bar" },
    { itemID = 2841,  name = "Bronze Bar" },
    { itemID = 3576,  name = "Tin Bar" },
    { itemID = 3575,  name = "Iron Bar" },
    { itemID = 3577,  name = "Gold Bar" },
    { itemID = 3859,  name = "Steel Bar" },
    { itemID = 3860,  name = "Mithril Bar" },
    { itemID = 3861,  name = "Blacksteel Bar" }, -- Unnused
    { itemID = 12359, name = "Thorium Bar" },
    { itemID = 6037,  name = "Truesilver Bar" },
    { itemID = 11371, name = "Dark Iron Bar" },
    { itemID = 12360, name = "Arcanite Bar" },
    { itemID = 12655, name = "Enchanted Thorium Bar" },
    { itemID = 17771, name = "Elementium Bar" },
    { itemID = 17203, name = "Sulfuron Ingot" },
  },
  ---@type PresetItemsDBItem[]
  lockbox = {
    -- Junkbox
    { itemID = 16882, name = "Battered Junkbox" },
    { itemID = 16883, name = "Worn Junkboxx" },
    { itemID = 16884, name = "Sturdy Junkboxx" },
    { itemID = 29569, name = "Strong Junkbox" },
    -- Lockbox
    { itemID = 4632,  name = "Ornate Bronze Lockbox" },
    { itemID = 4633,  name = "Heavy Bronze Lockbox" },
    { itemID = 4634,  name = "Iron Lockbox" },
    { itemID = 4636,  name = "Strong Iron Lockbox" },
    { itemID = 4637,  name = "Steel Lockbox" },
    { itemID = 4638,  name = "Reinforced Steel Lockbox" },
    { itemID = 5758,  name = "Mithril Lockbox" },
    { itemID = 5759,  name = "Thorium Lockbox" },
    { itemID = 5760,  name = "Eternium Lockbox" },
    { itemID = 31952, name = "Khorium Lockbox" },
  },
  ---@type PresetItemsDBItem[]
  zulGurubCurrency = {
    -- Coin
    { itemID = 19706, name = "Bloodscalp Coin" },
    { itemID = 21100, name = "Coin of Ancestry" },
    { itemID = 19701, name = "Gurubashi Coin" },
    { itemID = 19700, name = "Hakkari Coin" },
    { itemID = 19699, name = "Razzashi Coin" },
    { itemID = 19704, name = "Sandfury Coin" },
    { itemID = 19705, name = "Skullsplitter Coin" },
    { itemID = 19702, name = "Vilebranch Coin" },
    { itemID = 19703, name = "Witherbark Coin" },
    { itemID = 19698, name = "Zulian Coin" },
    -- Bijou
    { itemID = 19708, name = "Blue Hakkari Bijou" },
    { itemID = 19713, name = "Bronze Hakkari Bijou" },
    { itemID = 19715, name = "Gold Hakkari Bijou" },
    { itemID = 19711, name = "Green Hakkari Bijou" },
    { itemID = 19710, name = "Orange Hakkari Bijou" },
    { itemID = 19712, name = "Purple Hakkari Bijou" },
    { itemID = 19707, name = "Red Hakkari Bijou" },
    { itemID = 19714, name = "Silver Hakkari Bijou" },
    { itemID = 19709, name = "Yellow Hakkari Bijou" },
  },
  ---@type PresetItemsDBItem[]
  healthPotion = {
    { itemID = 858,   name = "Lesser Healing Potion" },
    { itemID = 4596,  name = "Discolored Healing Potion" },
    { itemID = 118,   name = "Minor Healing Potion" },
    { itemID = 929,   name = "Healing Potion" },
    { itemID = 1710,  name = "Greater Healing Potion" },
    { itemID = 3928,  name = "Superior Healing Potion" },
    { itemID = 18839, name = "Combat Healing Potion" },
    { itemID = 13446, name = "Major Healing Potion" },
    { itemID = 17348, name = "Major Healing Draught" },
  },
  ---@type PresetItemsDBItem[]
  manaPotion = {
    { itemID = 2455,  name = "Minor Mana Potion" },
    { itemID = 3385,  name = "Lesser Mana Potion" },
    { itemID = 3827,  name = "Mana Potion" },
    { itemID = 6149,  name = "Greater Mana Potion" },
    { itemID = 17352, name = "Superior Mana Draught" },
    { itemID = 13443, name = "Superior Mana Potion" },
    { itemID = 18841, name = "Combat Mana Potion" },
    { itemID = 17351, name = "Major Mana Draught" },
    { itemID = 13444, name = "Major Mana Potion" },
  },
  ---@type PresetItemsDBItem[]
  scroll = {
    { itemID = 1181,  name = "Scroll of Spirit" },
    { itemID = 3013,  name = "Scroll of Protection" },
    { itemID = 955,   name = "Scroll of Intellect" },
    { itemID = 1180,  name = "Scroll of Stamina" },
    { itemID = 3012,  name = "Scroll of Agility" },
    { itemID = 954,   name = "Scroll of Strength" },
    { itemID = 1712,  name = "Scroll of Spirit II" },
    { itemID = 1478,  name = "Scroll of Protection II" },
    { itemID = 2290,  name = "Scroll of Intellect II" },
    { itemID = 1711,  name = "Scroll of Stamina II" },
    { itemID = 2289,  name = "Scroll of Strength II" },
    { itemID = 1477,  name = "Scroll of Agility II" },
    { itemID = 4421,  name = "Scroll of Protection III" },
    { itemID = 4424,  name = "Scroll of Spirit III" },
    { itemID = 4422,  name = "Scroll of Stamina III" },
    { itemID = 4419,  name = "Scroll of Intellect III" },
    { itemID = 4425,  name = "Scroll of Agility III" },
    { itemID = 4426,  name = "Scroll of Strength III" },
    { itemID = 10305, name = "Scroll of Protection IV" },
    { itemID = 10306, name = "Scroll of Spirit IV" },
    { itemID = 10307, name = "Scroll of Stamina IV" },
    { itemID = 10308, name = "Scroll of Intellect IV" },
  },
  ---@type PresetItemsDBItem[]
  leather = {
    { itemID = 5116,  name = "Long Tail Feather" },
    { itemID = 6471,  name = "Perfect Deviate Scale" },
    { itemID = 6470,  name = "Deviate Scale" },
    { itemID = 7286,  name = "Black Whelp Scale" },
    { itemID = 7392,  name = "Green Whelp Scale" },
    { itemID = 2934,  name = "Ruined Leather Scraps" },
    { itemID = 2318,  name = "Light Leather" },
    { itemID = 783,   name = "Light Hide" },
    { itemID = 4289,  name = "Salt" },
    { itemID = 5082,  name = "Thin Kodo Leather" },
    { itemID = 4231,  name = "Cured Light Hide" },
    { itemID = 5784,  name = "Slimy Murloc Scale" },
    { itemID = 2319,  name = "Medium Leather" },
    { itemID = 4232,  name = "Medium Hide" },
    { itemID = 4233,  name = "Cured Medium Hide" },
    { itemID = 4234,  name = "Heavy Leather" },
    { itemID = 4235,  name = "Heavy Hide" },
    { itemID = 4461,  name = "Raptor Hide" },
    { itemID = 4236,  name = "Cured Heavy Hide" },
    { itemID = 7428,  name = "Shadowcat Hide" },
    { itemID = 8167,  name = "Turtle Scale" },
    { itemID = 5785,  name = "Thick Murloc Scale" },
    { itemID = 4304,  name = "Thick Leather" },
    { itemID = 8150,  name = "Deeprock Salt" },
    { itemID = 8368,  name = "Thick Wolfhide" },
    { itemID = 8172,  name = "Cured Thick Hide" },
    { itemID = 8169,  name = "Thick Hide" },
    { itemID = 8165,  name = "Worn Dragonscale" },
    { itemID = 8154,  name = "Scorpid Scale" },
    { itemID = 8168,  name = "Jet Black Feather" },
    { itemID = 8170,  name = "Rugged Leather" },
    { itemID = 15409, name = "Refined Deeprock Salt" },
    { itemID = 15407, name = "Cured Rugged Hide" },
    { itemID = 15417, name = "Devilsaur Leather" },
    { itemID = 15420, name = "Ironfeather" },
    { itemID = 15419, name = "Warbear Leather" },
    { itemID = 15422, name = "Frostsaber Leather" },
    { itemID = 8171,  name = "Rugged Hide" },
    { itemID = 15415, name = "Blue Dragonscale" },
    { itemID = 15423, name = "Chimera Leather" },
    { itemID = 15412, name = "Green Dragonscale" },
    { itemID = 15416, name = "Black Dragonscale" },
    { itemID = 12810, name = "Enchanted Leather" },
    { itemID = 15408, name = "Heavy Scorpid Scale" },
    { itemID = 20498, name = "Silithid Chitin" },
    { itemID = 20500, name = "Light Silithid Carapace" },
    { itemID = 20501, name = "Heavy Silithid Carapace" },
    { itemID = 15414, name = "Red Dragonscale" },
    { itemID = 25699, name = "Crystal Infused Leather" },
    { itemID = 19767, name = "Primal Bat Leather" },
    { itemID = 17012, name = "Core Leather" },
    { itemID = 15410, name = "Scale of Onyxia" },
    { itemID = 19768, name = "Primal Tiger Leather" },
    { itemID = 17967, name = "Refined Scale of Onyxia" },

  },
  ---@type PresetItemsDBItem[]
  rawCooking = {
    { itemID = 2665,  name = "Stormwind Seasoning Herbs" },
    { itemID = 23676, name = "Moongraze Stag Tenderloin" },
    { itemID = 27668, name = "Lynx Meat" },
    { itemID = 6291,  name = "Raw Brilliant Smallfish" },
    { itemID = 12223, name = "Meaty Bat Wing" },
    { itemID = 5465,  name = "Small Spider Leg" },
    { itemID = 27669, name = "Bat Flesh" },
    { itemID = 6303,  name = "Raw Slitherskin Mackerel" },
    { itemID = 769,   name = "Chunk of Boar Meat" },
    { itemID = 2672,  name = "Stringy Wolf Meat" },
    { itemID = 6889,  name = "Small Egg" },
    { itemID = 2886,  name = "Crag Boar Rib" },
    { itemID = 5466,  name = "Scorpid Stinger" },
    { itemID = 3174,  name = "Spider Ichor" },
    { itemID = 5469,  name = "Strider Meat" },
    { itemID = 729,   name = "Stringy Vulture Meat" },
    { itemID = 3172,  name = "Boar Intestines" },
    { itemID = 2673,  name = "Coyote Meat" },
    { itemID = 5467,  name = "Kodo Meat" },
    { itemID = 730,   name = "Murloc Eye" },
    { itemID = 3173,  name = "Bear Meat" },
    { itemID = 723,   name = "Goretusk Liver" },
    { itemID = 731,   name = "Goretusk Snout" },
    { itemID = 2674,  name = "Crawler Meat" },
    { itemID = 2675,  name = "Crawler Claw" },
    { itemID = 5503,  name = "Clam Meat" },
    { itemID = 2677,  name = "Boar Ribs" },
    { itemID = 2924,  name = "Crocolisk Meat" },
    { itemID = 22644, name = "Crunchy Spider Leg" },
    { itemID = 1081,  name = "Crisp Spider Meat" },
    { itemID = 6289,  name = "Raw Longjaw Mud Snapper" },
    { itemID = 6361,  name = "Raw Rainbow Fin Albacore" },
    { itemID = 1080,  name = "Tough Condor Meat" },
    { itemID = 5468,  name = "Soft Frenzy Flesh" },
    { itemID = 6317,  name = "Raw Loch Frenzy" },
    { itemID = 1468,  name = "Murloc Fin" },
    { itemID = 2296,  name = "Great Goretusk Snout" },
    { itemID = 1015,  name = "Lean Wolf Flank" },
    { itemID = 21071, name = "Raw Sagefish" },
    { itemID = 3730,  name = "Big Bear Meat" },
    { itemID = 3685,  name = "Raptor Egg" },
    { itemID = 5470,  name = "Thunder Lizard Tail" },
    { itemID = 5504,  name = "Tangy Clam Meat" },
    { itemID = 3667,  name = "Tender Crocolisk Meat" },
    { itemID = 3731,  name = "Lion Meat" },
    { itemID = 5471,  name = "Stag Meat" },
    { itemID = 6308,  name = "Raw Bristle Whisker Catfish" },
    { itemID = 2251,  name = "Gooey Spider Leg" },
    { itemID = 12203, name = "Red Wolf Meat" },
    { itemID = 12184, name = "Raptor Flesh" },
    { itemID = 12037, name = "Mystery Meat" },
    { itemID = 3712,  name = "Turtle Meat" },
    { itemID = 12202, name = "Tiger Meat" },
    { itemID = 8365,  name = "Raw Mithril Head Trout" },
    { itemID = 6362,  name = "Raw Rockscale Cod" },
    { itemID = 3404,  name = "Buzzard Wing" },
    { itemID = 4655,  name = "Giant Clam Meat" },
    { itemID = 12204, name = "Heavy Kodo Meat" },
    { itemID = 37588, name = "Mostly Digested Fish" },
    { itemID = 21153, name = "Raw Greater Sagefish" },
    { itemID = 12208, name = "Tender Wolf Meat" },
    { itemID = 12205, name = "White Spider Meat" },
    { itemID = 12206, name = "Tender Crab Meat" },
    { itemID = 7974,  name = "Zesty Clam Meat" },
    { itemID = 12207, name = "Giant Egg" },
    { itemID = 13759, name = "Raw Nightfin Snapper" },
    { itemID = 13760, name = "Raw Sunscale Salmon" },
    { itemID = 4603,  name = "Raw Spotted Yellowtail" },
    { itemID = 13758, name = "Raw Redgill" },
    { itemID = 13754, name = "Raw Glossy Mightfish" },
    { itemID = 13756, name = "Raw Summer Bass" },
    { itemID = 35562, name = "Bear Flank" },
    { itemID = 13889, name = "Raw Whitescale Salmon" },
    { itemID = 20424, name = "Sandworm Meat" },
    { itemID = 13888, name = "Darkclaw Lobster" },
    { itemID = 8959,  name = "Raw Spinefin Halibut" },
    { itemID = 21024, name = "Chimaerok Tenderloin" },
  },
};

---@class TBCItems
addonTable.tbcItems = {
  ---@type PresetItemsDBItem[]
  ore = {
    { itemID = 23424, name = "Fel Iron Ore" },
    { itemID = 12809, name = "Guardian Stone" },
    { itemID = 18562, name = "Elementium Ore" },
    { itemID = 23425, name = "Adamantite Ore" },
    { itemID = 23426, name = "Khorium Ore" },
    { itemID = 23427, name = "Eternium Ore" },
  },
  ---@type PresetItemsDBItem[]
  bar = {
    { itemID = 23448, name = "Felsteel Bar" },
    { itemID = 23445, name = "Fel Iron Bar" },
    { itemID = 17771, name = "Elementium Bar" },
    { itemID = 17203, name = "Sulfuron Ingot" },
    { itemID = 23573, name = "Hardened Adamantite Bar" },
    { itemID = 23446, name = "Adamantite Bar" },
    { itemID = 23449, name = "Khorium Bar" },
    { itemID = 23447, name = "Eternium Bar" },
    { itemID = 35128, name = "Hardened Khorium" },
  },
};

---@class PresetItemsDBItem
---@field itemID number
---@field name string
